# if v stays on 2, make all the grid numbers even

def make():
    grid=[]

    xt0=-2
    x0=36
    x1=68
    x2=116
    x3=164
    x4=212
    x5=260
    x6=308
    x7=356
    x8=404
    x9=436
    xt1=474
    
    y0=62
    y1=126
    y2=174
    y3=222
    y4=270
    y5=318
    y6=366
    y7=414
    y8=462
    y9=510

    i=xt0
    while i<=x3:
        grid+=[[i,y4]]
        i+=1
    i=x6
    while i<=xt1:
        grid+=[[i,y4]]
        i+=1
    
    i=x0
    while i<=x4:
        grid+=[[i,y0]]
        i+=1
    i=x5
    while i<=x9:
        grid+=[[i,y0]]
        i+=1
    i=x0
    while i<=x9:
        grid+=[[i,y1]]
        i+=1
    i=x0
    while i<=x2:
        grid+=[[i,y2]]
        i+=1
    i=x3
    while i<=x4:
        grid+=[[i,y2]]
        i+=1
    i=x5
    while i<=x6:
        grid+=[[i,y2]]
        i+=1
    i=x7
    while i<=x9:
        grid+=[[i,y2]]
        i+=1
    i=x3
    while i<=x6:
        grid+=[[i,y3]]
        i+=1
    i=x3
    while i<=x6:
        grid+=[[i,y5]]
        i+=1
    i=x0
    while i<=x4:
        grid+=[[i,y6]]
        i+=1
    i=x5
    while i<=x9:
        grid+=[[i,y6]]
        i+=1
    i=x0
    while i<=x1:
        grid+=[[i,y7]]
        i+=1
    i=x2
    while i<=x7:
        grid+=[[i,y7]]
        i+=1
    i=x8
    while i<=x9:
        grid+=[[i,y7]]
        i+=1
    i=x0
    while i<=x2:
        grid+=[[i,y8]]
        i+=1
    i=x3
    while i<=x4:
        grid+=[[i,y8]]
        i+=1
    i=x5
    while i<=x6:
        grid+=[[i,y8]]
        i+=1
    i=x7
    while i<=x9:
        grid+=[[i,y8]]
        i+=1
    i=x0
    while i<=x9:
        grid+=[[i,y9]]
        i+=1

    i=y0
    while i<=y2:
        grid+=[[x0,i]]
        i+=1
    i=y6
    while i<=y7:
        grid+=[[x0,i]]
        i+=1
    i=y8
    while i<=y9:
        grid+=[[x0,i]]
        i+=1
    i=y7
    while i<=y8:
        grid+=[[x1,i]]
        i+=1
    i=y0
    while i<=y8:
        grid+=[[x2,i]]
        i+=1
    i=y1
    while i<=y2:
        grid+=[[x3,i]]
        i+=1
    i=y3
    while i<=y6:
        grid+=[[x3,i]]
        i+=1
    i=y7
    while i<=y8:
        grid+=[[x3,i]]
        i+=1
    i=y0
    while i<=y1:
        grid+=[[x4,i]]
        i+=1
    i=y2
    while i<=y3:
        grid+=[[x4,i]]
        i+=1
    i=y6
    while i<=y7:
        grid+=[[x4,i]]
        i+=1
    i=y8
    while i<=y9:
        grid+=[[x4,i]]
        i+=1
    i=y0
    while i<=y1:
        grid+=[[x5,i]]
        i+=1
    i=y2
    while i<=y3:
        grid+=[[x5,i]]
        i+=1
    i=y6
    while i<=y7:
        grid+=[[x5,i]]
        i+=1
    i=y8
    while i<=y9:
        grid+=[[x5,i]]
        i+=1
    i=y1
    while i<=y2:
        grid+=[[x6,i]]
        i+=1
    i=y3
    while i<=y6:
        grid+=[[x6,i]]
        i+=1
    i=y7
    while i<=y8:
        grid+=[[x6,i]]
        i+=1
    i=y0
    while i<=y8:
        grid+=[[x7,i]]
        i+=1
    i=y7
    while i<=y8:
        grid+=[[x8,i]]
        i+=1
    i=y0
    while i<=y2:
        grid+=[[x9,i]]
        i+=1
    i=y6
    while i<=y7:
        grid+=[[x9,i]]
        i+=1
    i=y8
    while i<=y9:
        grid+=[[x9,i]]
        i+=1
    
    return grid
